classdef LaneArray < robotics.ros.Message
    %LaneArray MATLAB implementation of waypoint_follower/LaneArray
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'waypoint_follower/LaneArray' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '92d871fae788ffe89a2471f84797cb3e' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        WaypointFollowerLaneClass = robotics.ros.msg.internal.MessageFactory.getClassForType('waypoint_follower/lane') % Dispatch to MATLAB class for message type waypoint_follower/lane
    end
    
    properties (Dependent)
        Lanes
    end
    
    properties (Access = protected)
        Cache = struct('Lanes', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Lanes'} % List of non-constant message properties
        ROSPropertyList = {'lanes'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = LaneArray(msg)
            %LaneArray Construct the message object LaneArray
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function lanes = get.Lanes(obj)
            %get.Lanes Get the value for property Lanes
            if isempty(obj.Cache.Lanes)
                javaArray = obj.JavaMessage.getLanes;
                array = obj.readJavaArray(javaArray, obj.WaypointFollowerLaneClass);
                obj.Cache.Lanes = feval(obj.WaypointFollowerLaneClass, array);
            end
            lanes = obj.Cache.Lanes;
        end
        
        function set.Lanes(obj, lanes)
            %set.Lanes Set the value for property Lanes
            if ~isvector(lanes) && isempty(lanes)
                % Allow empty [] input
                lanes = feval([obj.WaypointFollowerLaneClass '.empty'], 0, 1);
            end
            
            validateattributes(lanes, {obj.WaypointFollowerLaneClass}, {'vector'}, 'LaneArray', 'Lanes');
            
            javaArray = obj.JavaMessage.getLanes;
            array = obj.writeJavaArray(lanes, javaArray, obj.WaypointFollowerLaneClass);
            obj.JavaMessage.setLanes(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Lanes)
                obj.Cache.Lanes = [];
                obj.Cache.Lanes = obj.Lanes;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Lanes = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Lanes = copy(obj.Lanes);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            LanesCell = arrayfun(@(x) feval([obj.WaypointFollowerLaneClass '.loadobj'], x), strObj.Lanes, 'UniformOutput', false);
            obj.Lanes = vertcat(LanesCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Lanes = arrayfun(@(x) saveobj(x), obj.Lanes);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.waypoint_follower.LaneArray.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.waypoint_follower.LaneArray;
            obj.reload(strObj);
        end
    end
end
