classdef waypoint < robotics.ros.Message
    %waypoint MATLAB implementation of waypoint_follower/waypoint
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'waypoint_follower/waypoint' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '8ec154b89b8eb7d6a4ce8fec41588dc0' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPoseStampedClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/PoseStamped') % Dispatch to MATLAB class for message type geometry_msgs/PoseStamped
        GeometryMsgsTwistStampedClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/TwistStamped') % Dispatch to MATLAB class for message type geometry_msgs/TwistStamped
        WaypointFollowerDtlaneClass = robotics.ros.msg.internal.MessageFactory.getClassForType('waypoint_follower/dtlane') % Dispatch to MATLAB class for message type waypoint_follower/dtlane
    end
    
    properties (Dependent)
        Pose
        Twist
        Dtlane
    end
    
    properties (Access = protected)
        Cache = struct('Pose', [], 'Twist', [], 'Dtlane', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Dtlane', 'Pose', 'Twist'} % List of non-constant message properties
        ROSPropertyList = {'dtlane', 'pose', 'twist'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = waypoint(msg)
            %waypoint Construct the message object waypoint
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function pose = get.Pose(obj)
            %get.Pose Get the value for property Pose
            if isempty(obj.Cache.Pose)
                obj.Cache.Pose = feval(obj.GeometryMsgsPoseStampedClass, obj.JavaMessage.getPose);
            end
            pose = obj.Cache.Pose;
        end
        
        function set.Pose(obj, pose)
            %set.Pose Set the value for property Pose
            validateattributes(pose, {obj.GeometryMsgsPoseStampedClass}, {'nonempty', 'scalar'}, 'waypoint', 'Pose');
            
            obj.JavaMessage.setPose(pose.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Pose)
                obj.Cache.Pose.setJavaObject(pose.getJavaObject);
            end
        end
        
        function twist = get.Twist(obj)
            %get.Twist Get the value for property Twist
            if isempty(obj.Cache.Twist)
                obj.Cache.Twist = feval(obj.GeometryMsgsTwistStampedClass, obj.JavaMessage.getTwist);
            end
            twist = obj.Cache.Twist;
        end
        
        function set.Twist(obj, twist)
            %set.Twist Set the value for property Twist
            validateattributes(twist, {obj.GeometryMsgsTwistStampedClass}, {'nonempty', 'scalar'}, 'waypoint', 'Twist');
            
            obj.JavaMessage.setTwist(twist.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Twist)
                obj.Cache.Twist.setJavaObject(twist.getJavaObject);
            end
        end
        
        function dtlane = get.Dtlane(obj)
            %get.Dtlane Get the value for property Dtlane
            if isempty(obj.Cache.Dtlane)
                obj.Cache.Dtlane = feval(obj.WaypointFollowerDtlaneClass, obj.JavaMessage.getDtlane);
            end
            dtlane = obj.Cache.Dtlane;
        end
        
        function set.Dtlane(obj, dtlane)
            %set.Dtlane Set the value for property Dtlane
            validateattributes(dtlane, {obj.WaypointFollowerDtlaneClass}, {'nonempty', 'scalar'}, 'waypoint', 'Dtlane');
            
            obj.JavaMessage.setDtlane(dtlane.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Dtlane)
                obj.Cache.Dtlane.setJavaObject(dtlane.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Pose = [];
            obj.Cache.Twist = [];
            obj.Cache.Dtlane = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Pose = copy(obj.Pose);
            cpObj.Twist = copy(obj.Twist);
            cpObj.Dtlane = copy(obj.Dtlane);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Pose = feval([obj.GeometryMsgsPoseStampedClass '.loadobj'], strObj.Pose);
            obj.Twist = feval([obj.GeometryMsgsTwistStampedClass '.loadobj'], strObj.Twist);
            obj.Dtlane = feval([obj.WaypointFollowerDtlaneClass '.loadobj'], strObj.Dtlane);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Pose = saveobj(obj.Pose);
            strObj.Twist = saveobj(obj.Twist);
            strObj.Dtlane = saveobj(obj.Dtlane);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.waypoint_follower.waypoint.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.waypoint_follower.waypoint;
            obj.reload(strObj);
        end
    end
end
