simulink;
new_system('lane_select');
add_block('robotlib/Blank Message', 'lane_select/waypoint_follower::lane');
set_param('lane_select/waypoint_follower::lane', 'messageType', 'waypoint_follower/lane');
set_param('lane_select/waypoint_follower::lane', 'Position', [70, 50, 200, 120]);
portpm0 = get_param('lane_select/waypoint_follower::lane', 'PortHandles');
add_block('simulink/Signal Routing/Bus Assignment', 'lane_select/BusA0');
set_param('lane_select/BusA0', 'Position', [250, 70, 295, 120]);
portA0 = get_param('lane_select/BusA0', 'PortHandles');
add_block('robotlib/Publish','lane_select/base_waypoints');
set_param('lane_select/base_waypoints', 'topicSource', 'Specify your own');
set_param('lane_select/base_waypoints', 'topic', '/base_waypoints');
set_param('lane_select/base_waypoints', 'messageType', 'waypoint_follower/lane');
set_param('lane_select/base_waypoints', 'Position', [345, 65, 475, 135]);
portp0 = get_param('lane_select/base_waypoints', 'PortHandles');
add_line('lane_select', portpm0.Outport, portA0.Inport(1));
add_line('lane_select', portA0.Outport, portp0.Inport);
add_block('robotlib/Subscribe', 'lane_select/config::lane_select');
set_param('lane_select/config::lane_select', 'topicSource', 'Specify your own');
set_param('lane_select/config::lane_select', 'topic', '/config/lane_select');
set_param('lane_select/config::lane_select', 'messageType', 'runtime_manager/ConfigLaneSelect');
set_param('lane_select/config::lane_select', 'Position', [70, 200, 200, 270]);
ports1 = get_param('lane_select/config::lane_select', 'PortHandles');
add_block('simulink/Sinks/Terminator', 'lane_select/Term1');
set_param('lane_select/Term1', 'Position', [275, 210, 295, 230]);
portT1 = get_param('lane_select/Term1', 'PortHandles');
add_block('simulink/Signal Routing/Bus Selector', 'lane_select/BusS1');
set_param('lane_select/BusS1', 'Position', [250, 235, 295, 270]);
portS1 = get_param('lane_select/BusS1', 'PortHandles');
add_line('lane_select', ports1.Outport(1), portT1.Inport);
add_line('lane_select', ports1.Outport(2), portS1.Inport);
add_block('robotlib/Subscribe', 'lane_select/traffic_waypoints_array');
set_param('lane_select/traffic_waypoints_array', 'topicSource', 'Specify your own');
set_param('lane_select/traffic_waypoints_array', 'topic', '/traffic_waypoints_array');
set_param('lane_select/traffic_waypoints_array', 'messageType', 'waypoint_follower/LaneArray');
set_param('lane_select/traffic_waypoints_array', 'Position', [70, 350, 200, 420]);
ports2 = get_param('lane_select/traffic_waypoints_array', 'PortHandles');
add_block('simulink/Sinks/Terminator', 'lane_select/Term2');
set_param('lane_select/Term2', 'Position', [275, 360, 295, 380]);
portT2 = get_param('lane_select/Term2', 'PortHandles');
add_block('simulink/Signal Routing/Bus Selector', 'lane_select/BusS2');
set_param('lane_select/BusS2', 'Position', [250, 385, 295, 420]);
portS2 = get_param('lane_select/BusS2', 'PortHandles');
add_line('lane_select', ports2.Outport(1), portT2.Inport);
add_line('lane_select', ports2.Outport(2), portS2.Inport);
save_system('lane_select');
