simulink;
new_system('lane_navi');
add_block('robotlib/Blank Message', 'lane_navi/waypoint_follower::LaneArray0');
set_param('lane_navi/waypoint_follower::LaneArray0', 'messageType', 'waypoint_follower/LaneArray');
set_param('lane_navi/waypoint_follower::LaneArray0', 'Position', [70, 50, 200, 120]);
portpm0 = get_param('lane_navi/waypoint_follower::LaneArray0', 'PortHandles');
add_block('simulink/Signal Routing/Bus Assignment', 'lane_navi/BusA0');
set_param('lane_navi/BusA0', 'Position', [250, 70, 295, 120]);
portA0 = get_param('lane_navi/BusA0', 'PortHandles');
add_block('robotlib/Publish','lane_navi/lane_waypoints_array');
set_param('lane_navi/lane_waypoints_array', 'topicSource', 'Specify your own');
set_param('lane_navi/lane_waypoints_array', 'topic', '/lane_waypoints_array');
set_param('lane_navi/lane_waypoints_array', 'messageType', 'waypoint_follower/LaneArray');
set_param('lane_navi/lane_waypoints_array', 'Position', [345, 65, 475, 135]);
portp0 = get_param('lane_navi/lane_waypoints_array', 'PortHandles');
add_line('lane_navi', portpm0.Outport, portA0.Inport(1));
add_line('lane_navi', portA0.Outport, portp0.Inport);
add_block('robotlib/Subscribe', 'lane_navi/vector_map_info::lane');
set_param('lane_navi/vector_map_info::lane', 'topicSource', 'Specify your own');
set_param('lane_navi/vector_map_info::lane', 'topic', '/vector_map_info/lane');
set_param('lane_navi/vector_map_info::lane', 'messageType', 'vector_map_msgs/LaneArray');
set_param('lane_navi/vector_map_info::lane', 'Position', [70, 200, 200, 270]);
ports1 = get_param('lane_navi/vector_map_info::lane', 'PortHandles');
add_block('simulink/Sinks/Terminator', 'lane_navi/Term1');
set_param('lane_navi/Term1', 'Position', [275, 210, 295, 230]);
portT1 = get_param('lane_navi/Term1', 'PortHandles');
add_block('simulink/Signal Routing/Bus Selector', 'lane_navi/BusS1');
set_param('lane_navi/BusS1', 'Position', [250, 235, 295, 270]);
portS1 = get_param('lane_navi/BusS1', 'PortHandles');
add_line('lane_navi', ports1.Outport(1), portT1.Inport);
add_line('lane_navi', ports1.Outport(2), portS1.Inport);
add_block('robotlib/Subscribe', 'lane_navi/vector_map_info::point');
set_param('lane_navi/vector_map_info::point', 'topicSource', 'Specify your own');
set_param('lane_navi/vector_map_info::point', 'topic', '/vector_map_info/point');
set_param('lane_navi/vector_map_info::point', 'messageType', 'vector_map_msgs/PointArray');
set_param('lane_navi/vector_map_info::point', 'Position', [70, 350, 200, 420]);
ports2 = get_param('lane_navi/vector_map_info::point', 'PortHandles');
add_block('simulink/Sinks/Terminator', 'lane_navi/Term2');
set_param('lane_navi/Term2', 'Position', [275, 360, 295, 380]);
portT2 = get_param('lane_navi/Term2', 'PortHandles');
add_block('simulink/Signal Routing/Bus Selector', 'lane_navi/BusS2');
set_param('lane_navi/BusS2', 'Position', [250, 385, 295, 420]);
portS2 = get_param('lane_navi/BusS2', 'PortHandles');
add_line('lane_navi', ports2.Outport(1), portT2.Inport);
add_line('lane_navi', ports2.Outport(2), portS2.Inport);
add_block('robotlib/Subscribe', 'lane_navi/vector_map_info::node');
set_param('lane_navi/vector_map_info::node', 'topicSource', 'Specify your own');
set_param('lane_navi/vector_map_info::node', 'topic', '/vector_map_info/node');
set_param('lane_navi/vector_map_info::node', 'messageType', 'vector_map_msgs/NodeArray');
set_param('lane_navi/vector_map_info::node', 'Position', [70, 500, 200, 570]);
ports3 = get_param('lane_navi/vector_map_info::node', 'PortHandles');
add_block('simulink/Sinks/Terminator', 'lane_navi/Term3');
set_param('lane_navi/Term3', 'Position', [275, 510, 295, 530]);
portT3 = get_param('lane_navi/Term3', 'PortHandles');
add_block('simulink/Signal Routing/Bus Selector', 'lane_navi/BusS3');
set_param('lane_navi/BusS3', 'Position', [250, 535, 295, 570]);
portS3 = get_param('lane_navi/BusS3', 'PortHandles');
add_line('lane_navi', ports3.Outport(1), portT3.Inport);
add_line('lane_navi', ports3.Outport(2), portS3.Inport);
add_block('robotlib/Subscribe', 'lane_navi/route_cmd');
set_param('lane_navi/route_cmd', 'topicSource', 'Specify your own');
set_param('lane_navi/route_cmd', 'topic', '/route_cmd');
set_param('lane_navi/route_cmd', 'messageType', 'tablet_socket/route_cmd');
set_param('lane_navi/route_cmd', 'Position', [70, 650, 200, 720]);
ports4 = get_param('lane_navi/route_cmd', 'PortHandles');
add_block('simulink/Sinks/Terminator', 'lane_navi/Term4');
set_param('lane_navi/Term4', 'Position', [275, 660, 295, 680]);
portT4 = get_param('lane_navi/Term4', 'PortHandles');
add_block('simulink/Signal Routing/Bus Selector', 'lane_navi/BusS4');
set_param('lane_navi/BusS4', 'Position', [250, 685, 295, 720]);
portS4 = get_param('lane_navi/BusS4', 'PortHandles');
add_line('lane_navi', ports4.Outport(1), portT4.Inport);
add_line('lane_navi', ports4.Outport(2), portS4.Inport);
save_system('lane_navi');
