classdef ConfigLaneRule < robotics.ros.Message
    %ConfigLaneRule MATLAB implementation of runtime_manager/ConfigLaneRule
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'runtime_manager/ConfigLaneRule' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'e297624d23dcc2f31641d9b1ac9dd61f' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Acceleration
        NumberOfZerosAhead
        NumberOfZerosBehind
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Acceleration', 'Header', 'NumberOfZerosAhead', 'NumberOfZerosBehind'} % List of non-constant message properties
        ROSPropertyList = {'acceleration', 'header', 'number_of_zeros_ahead', 'number_of_zeros_behind'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ConfigLaneRule(msg)
            %ConfigLaneRule Construct the message object ConfigLaneRule
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'ConfigLaneRule', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function acceleration = get.Acceleration(obj)
            %get.Acceleration Get the value for property Acceleration
            acceleration = single(obj.JavaMessage.getAcceleration);
        end
        
        function set.Acceleration(obj, acceleration)
            %set.Acceleration Set the value for property Acceleration
            validateattributes(acceleration, {'numeric'}, {'nonempty', 'scalar'}, 'ConfigLaneRule', 'Acceleration');
            
            obj.JavaMessage.setAcceleration(acceleration);
        end
        
        function numberofzerosahead = get.NumberOfZerosAhead(obj)
            %get.NumberOfZerosAhead Get the value for property NumberOfZerosAhead
            numberofzerosahead = int32(obj.JavaMessage.getNumberOfZerosAhead);
        end
        
        function set.NumberOfZerosAhead(obj, numberofzerosahead)
            %set.NumberOfZerosAhead Set the value for property NumberOfZerosAhead
            validateattributes(numberofzerosahead, {'numeric'}, {'nonempty', 'scalar'}, 'ConfigLaneRule', 'NumberOfZerosAhead');
            
            obj.JavaMessage.setNumberOfZerosAhead(numberofzerosahead);
        end
        
        function numberofzerosbehind = get.NumberOfZerosBehind(obj)
            %get.NumberOfZerosBehind Get the value for property NumberOfZerosBehind
            numberofzerosbehind = int32(obj.JavaMessage.getNumberOfZerosBehind);
        end
        
        function set.NumberOfZerosBehind(obj, numberofzerosbehind)
            %set.NumberOfZerosBehind Set the value for property NumberOfZerosBehind
            validateattributes(numberofzerosbehind, {'numeric'}, {'nonempty', 'scalar'}, 'ConfigLaneRule', 'NumberOfZerosBehind');
            
            obj.JavaMessage.setNumberOfZerosBehind(numberofzerosbehind);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Acceleration = obj.Acceleration;
            cpObj.NumberOfZerosAhead = obj.NumberOfZerosAhead;
            cpObj.NumberOfZerosBehind = obj.NumberOfZerosBehind;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Acceleration = strObj.Acceleration;
            obj.NumberOfZerosAhead = strObj.NumberOfZerosAhead;
            obj.NumberOfZerosBehind = strObj.NumberOfZerosBehind;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Acceleration = obj.Acceleration;
            strObj.NumberOfZerosAhead = obj.NumberOfZerosAhead;
            strObj.NumberOfZerosBehind = obj.NumberOfZerosBehind;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.runtime_manager.ConfigLaneRule.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.runtime_manager.ConfigLaneRule;
            obj.reload(strObj);
        end
    end
end
