classdef ConfigRingFilter < robotics.ros.Message
    %ConfigRingFilter MATLAB implementation of runtime_manager/ConfigRingFilter
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'runtime_manager/ConfigRingFilter' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'b2962bd173a548074fde20317048312c' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        RingDiv
        VoxelLeafSize
    end
    
    properties (Constant, Hidden)
        PropertyList = {'RingDiv', 'VoxelLeafSize'} % List of non-constant message properties
        ROSPropertyList = {'ring_div', 'voxel_leaf_size'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ConfigRingFilter(msg)
            %ConfigRingFilter Construct the message object ConfigRingFilter
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function ringdiv = get.RingDiv(obj)
            %get.RingDiv Get the value for property RingDiv
            ringdiv = int32(obj.JavaMessage.getRingDiv);
        end
        
        function set.RingDiv(obj, ringdiv)
            %set.RingDiv Set the value for property RingDiv
            validateattributes(ringdiv, {'numeric'}, {'nonempty', 'scalar'}, 'ConfigRingFilter', 'RingDiv');
            
            obj.JavaMessage.setRingDiv(ringdiv);
        end
        
        function voxelleafsize = get.VoxelLeafSize(obj)
            %get.VoxelLeafSize Get the value for property VoxelLeafSize
            voxelleafsize = single(obj.JavaMessage.getVoxelLeafSize);
        end
        
        function set.VoxelLeafSize(obj, voxelleafsize)
            %set.VoxelLeafSize Set the value for property VoxelLeafSize
            validateattributes(voxelleafsize, {'numeric'}, {'nonempty', 'scalar'}, 'ConfigRingFilter', 'VoxelLeafSize');
            
            obj.JavaMessage.setVoxelLeafSize(voxelleafsize);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.RingDiv = obj.RingDiv;
            cpObj.VoxelLeafSize = obj.VoxelLeafSize;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.RingDiv = strObj.RingDiv;
            obj.VoxelLeafSize = strObj.VoxelLeafSize;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.RingDiv = obj.RingDiv;
            strObj.VoxelLeafSize = obj.VoxelLeafSize;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.runtime_manager.ConfigRingFilter.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.runtime_manager.ConfigRingFilter;
            obj.reload(strObj);
        end
    end
end
